AWSTemplateFormatVersion: '2010-09-09'

Resources:

### S3 Bucket（Web）
  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html

### S3 Policy
  WebBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${WebBucket.Arn}/*"

### CloudFront
  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - DomainName: !GetAtt WebBucket.DomainName
            Id: S3Origin
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false

### CodeBuild
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: ReactBuild
      Source:
        Type: GITHUB
        Location: https://github.com/あなたのID/リポジトリ名
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::アカウントID:role/service-role/codebuild-role
      Artifacts:
        Type: S3
        Location: !Ref WebBucket
        Packaging: NONE
